USE trabalhos;

CREATE TABLE IF NOT EXISTS ALUNOS (

	matricula	VARCHAR(9)		NOT NULL,
    nome		VARCHAR(100)	NOT NULL,
    email		VARCHAR(50)		NOT NULL,
    media		FLOAT,
    
	PRIMARY KEY (matricula)
);

CREATE TABLE IF NOT EXISTS TRABALHOS (

	id			INT				NOT NULL	AUTO_INCREMENT,
	aluno		VARCHAR(9)		NOT NULL,
    slide		VARCHAR(3)		NOT NULL,
    assunto		VARCHAR(20)		NOT NULL,
    codigo		TEXT			NOT NULL,
    correto		VARCHAR(50)		NOT NULL,

	PRIMARY KEY (id)
);

SELECT * FROM ALUNOS;
SELECT * FROM TRABALHOS;

SELECT COUNT(id)
FROM TRABALHOS 
WHERE TRABALHOS.correto = 1 AND TRABALHOS.aluno = '21201414';